#ifndef NETERRCODE_H
#define NETERRCODE_H

#define     NETERRCODE_NOTCREATETCPSOCKETOBJ         1001
#define     NETERRCODE_TCPSOCKEROBJISCREATED         1002
#define     NETERRCODE_TCPSOCKETOBJISNULL            1003
#define     NETERRCODE_STATEISCONNECTED              1004

#define     NETERRCODE_TIMEROBJISCREATED             1005
#define     NETERRCODE_NOTCREATETIMEROBJ             1006





#endif // NETERRCODE_H
